# Generated by Django 5.0.7 on 2024-08-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ad_additionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_hold',
            field=models.BooleanField(default=True, verbose_name='On hold'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_sold',
            field=models.BooleanField(default=True, verbose_name='Sold'),
        ),
    ]
